#!/bin/bash

# Test JavaScript debugging w przeglądarce
echo "=== AUTO-REFRESH DEBUG TEST ==="
echo "1. Otwórz przeglądarkę i przejdź do: http://localhost:8000/accounts/login/"
echo "2. Zaloguj się jako admin / admin123"
echo "3. Przejdź do: http://localhost:8000/ml/model/92/"
echo "4. Otwórz DevTools (F12) i przejdź do zakładki Console"
echo "5. Sprawdź, czy widzisz logi ModelDetailManager"
echo ""
echo "Oczekiwane logi:"
echo "  - ModelDetailManager: Initializing for model 92"
echo "  - ModelDetailManager: Element check: (sprawdź czy elementy są znalezione)"
echo "  - ModelDetailManager: Status detection: (sprawdź statusValue)"
echo "  - ModelDetailManager: Starting updates for model status: training (jeśli model jest w treningu)"
echo ""
echo "6. Jeśli auto-refresh się uruchomił, co 2 sekundy powinny pojawiać się żądania do /ml/model/92/progress/"
echo "7. W zakładce Network sprawdź, czy są żądania AJAX do progress endpoint"
echo ""
echo "Aktualny status modelu 92:"
sqlite3 data/db.sqlite3 "SELECT id, name, status, current_epoch, current_batch FROM ml_manager_mlmodel WHERE id = 92;"
echo ""
echo "Test API (czy zwraca poprawne dane):"
echo "curl -s 'http://localhost:8000/ml/model/92/progress/' | head -10"
