# Generated by Django 5.2.2 on 2025-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0002_mlmodel_is_registered_mlmodel_registry_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='training_process_id',
            field=models.IntegerField(blank=True, help_text='Process ID of training job', null=True),
        ),
    ]
