# Generated by Django 5.2.2 on 2025-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0003_mlmodel_training_process_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='training_process_id',
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('loading', 'Loading Dataset'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived'), ('deployed', 'Deployed')], default='pending', max_length=20),
        ),
    ]
