# Generated by Django 5.2.2 on 2025-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0004_remove_mlmodel_training_process_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(blank=True, help_text='Model architecture type (e.g., unet, unet-old)', max_length=50),
        ),
    ]
