# Generated by Django 5.2.2 on 2025-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0006_alter_mlmodel_registry_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplate',
            name='resolution',
            field=models.CharField(choices=[('original', 'Original Size'), ('128', '128 x 128 pixels'), ('256', '256 x 256 pixels'), ('384', '384 x 384 pixels'), ('512', '512 x 512 pixels')], default='256', help_text='Training image resolution. Higher resolutions require more memory.', max_length=20),
        ),
    ]
