# Generated by Django 4.2.23 on 2025-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0011_trainingtemplate_elastic_alpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplate',
            name='optimizer',
            field=models.CharField(choices=[('adam', 'Adam'), ('sgd', 'SGD'), ('rmsprop', 'RMSprop'), ('adamw', 'AdamW')], default='adam', help_text='Optimizer to use for training', max_length=20),
        ),
    ]
