# Generated by Django 4.2.23 on 2025-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0012_trainingtemplate_optimizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplate',
            name='lr_factor',
            field=models.FloatField(default=0.5, help_text='Factor to reduce learning rate'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='lr_gamma',
            field=models.FloatField(default=0.1, help_text='Gamma for step/exponential scheduler'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='lr_patience',
            field=models.IntegerField(default=5, help_text='Patience for plateau scheduler'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='lr_scheduler',
            field=models.CharField(choices=[('none', 'None'), ('plateau', 'ReduceLROnPlateau'), ('step', 'StepLR'), ('exponential', 'ExponentialLR'), ('cosine', 'CosineAnnealingLR'), ('adaptive', 'Custom Adaptive')], default='none', help_text='Learning rate scheduler type', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='lr_step_size',
            field=models.IntegerField(default=10, help_text='Step size for step scheduler'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='min_lr',
            field=models.FloatField(default=1e-07, help_text='Minimum learning rate'),
        ),
    ]
