# Generated by Django 4.2.23 on 2025-06-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0013_trainingtemplate_lr_factor_trainingtemplate_lr_gamma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplate',
            name='early_stopping_metric',
            field=models.CharField(choices=[('val_dice', 'Validation Dice Score'), ('val_loss', 'Validation Loss'), ('val_accuracy', 'Validation Accuracy')], default='val_dice', help_text='Metric to monitor for early stopping', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='early_stopping_min_delta',
            field=models.FloatField(default=0.0001, help_text='Minimum improvement required to reset patience'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='early_stopping_min_epochs',
            field=models.IntegerField(default=20, help_text='Minimum epochs before early stopping can occur'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='early_stopping_patience',
            field=models.IntegerField(default=10, help_text='Epochs to wait for improvement before stopping'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='use_early_stopping',
            field=models.BooleanField(default=False, help_text='Enable early stopping during training'),
        ),
    ]
