# Generated by Django 4.2.23 on 2025-06-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0014_trainingtemplate_early_stopping_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='training_logs',
            field=models.TextField(blank=True, help_text='Training logs and error messages', null=True),
        ),
    ]
