# Generated by Django 4.2.23 on 2025-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0015_mlmodel_training_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplate',
            name='use_pos_neg_cropping',
            field=models.BooleanField(default=False, help_text='Use RandCropByPosNegLabeld for better segmentation cropping (samples positive and negative regions)'),
        ),
    ]
