# Generated by Django 4.2.23 on 2025-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0016_trainingtemplate_use_pos_neg_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='process_id',
            field=models.IntegerField(blank=True, help_text='Process ID of the training process', null=True),
        ),
        migrations.AlterField(
            model_name='trainingtemplate',
            name='num_workers',
            field=models.IntegerField(default=1),
        ),
    ]
