# Generated by Django 4.2.23 on 2025-06-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0017_add_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplate',
            name='threshold',
            field=models.FloatField(default=0.5, help_text='Binary segmentation threshold for hard predictions (0.1-0.9)'),
        ),
    ]
