# Generated by Django 4.2.23 on 2025-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0018_trainingtemplate_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplate',
            name='clahe_clip_limit',
            field=models.FloatField(default=3.0, help_text='CLAHE clip limit for contrast enhancement (1.0-8.0)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='clahe_tile_size',
            field=models.IntegerField(default=8, help_text='CLAHE tile grid size (4-16)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='custom_preprocessing_pipeline',
            field=models.CharField(blank=True, help_text='Custom preprocessing pipeline (comma-separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='frangi_sigma_max',
            field=models.FloatField(default=10.0, help_text='Maximum sigma for Frangi filter (detects thick vessels)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='frangi_sigma_min',
            field=models.FloatField(default=1.0, help_text='Minimum sigma for Frangi filter (detects thin vessels)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='frangi_sigma_step',
            field=models.FloatField(default=2.0, help_text='Step size for sigma range (1.0-3.0)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='gamma_correction',
            field=models.FloatField(default=1.0, help_text='Gamma correction (0.5-2.0, 1.0=no correction)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='noise_reduction_sigma',
            field=models.FloatField(default=1.0, help_text='Noise reduction strength (0.5-3.0)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='normalize_intensity',
            field=models.BooleanField(default=True, help_text='Normalize image intensity to standard range'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='preprocessing_type',
            field=models.CharField(choices=[('angiography', 'Angiography (X-ray coronary images)'), ('ct_coronary', 'CT Coronary Angiography'), ('oct_coronary', 'OCT Coronary Images'), ('general', 'General Medical Images')], default='angiography', help_text='Type of medical imaging modality', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='unsharp_amount',
            field=models.FloatField(default=1.0, help_text='Unsharp masking strength (0.5-2.0)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='unsharp_radius',
            field=models.FloatField(default=1.0, help_text='Unsharp masking radius (0.5-3.0)'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='use_denoising',
            field=models.BooleanField(default=False, help_text='Enable denoising filters to reduce image noise'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='use_frangi_filter',
            field=models.BooleanField(default=False, help_text='Enable Frangi vesselness filter for vessel enhancement'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='use_histogram_equalization',
            field=models.BooleanField(default=False, help_text='Enable histogram equalization for global contrast'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='use_medical_preprocessing',
            field=models.BooleanField(default=False, help_text='Enable advanced medical image preprocessing'),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='use_unsharp_masking',
            field=models.BooleanField(default=False, help_text='Enable unsharp masking for edge enhancement'),
        ),
    ]
