# Generated by Django 4.2.23 on 2025-06-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0019_trainingtemplate_clahe_clip_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('loading', 'Loading Dataset'), ('training', 'Training'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('archived', 'Archived'), ('deployed', 'Deployed')], default='pending', max_length=20),
        ),
    ]
