# Generated by Django 4.2.23 on 2025-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0020_alter_mlmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='best_val_iou',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='train_iou',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='val_iou',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='segmentation_metric',
            field=models.CharField(choices=[('dice', 'Dice Score'), ('iou', 'IoU Score')], default='dice', help_text='Primary segmentation metric to track and display', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingtemplate',
            name='early_stopping_metric',
            field=models.CharField(choices=[('val_dice', 'Validation Dice Score'), ('val_iou', 'Validation IoU Score'), ('val_loss', 'Validation Loss'), ('val_accuracy', 'Validation Accuracy')], default='val_dice', help_text='Metric to monitor for early stopping', max_length=20),
        ),
    ]
