# Generated by Django 4.2.23 on 2025-07-03 20:51

import core.apps.ml_manager.models
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0021_mlmodel_best_val_iou_mlmodel_train_iou_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='inference/inputs/%Y/%m/%d/')),
                ('input_filename', models.CharField(help_text='Original filename of uploaded image', max_length=255)),
                ('output_mask', models.ImageField(blank=True, null=True, upload_to='inference/outputs/%Y/%m/%d/')),
                ('output_overlay', models.ImageField(blank=True, null=True, upload_to='inference/overlays/%Y/%m/%d/')),
                ('inference_config', models.JSONField(default=core.apps.ml_manager.models.default_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Inference configuration used')),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('detected_objects_count', models.IntegerField(default=0, help_text='Number of detected objects')),
                ('total_area_pixels', models.IntegerField(default=0, help_text='Total segmented area in pixels')),
                ('confidence_scores', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Confidence scores for detected objects')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if inference failed')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_results', to='ml_manager.mlmodel')),
            ],
            options={
                'verbose_name': 'Inference Result',
                'verbose_name_plural': 'Inference Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
