# Generated by Django 4.2.23 on 2025-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0022_inferenceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceresult',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for asynchronous processing', max_length=100, null=True),
        ),
    ]
