# Generated by Django 4.2.23 on 2025-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0024_trainingtemplate_custom_validation_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtemplate',
            name='epochs',
            field=models.IntegerField(default=1),
        ),
    ]
