# Generated by Django 4.2.23 on 2025-07-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0025_alter_trainingtemplate_epochs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='primary_metric_name',
            field=models.CharField(default='Dice', help_text='Display name for primary metric', max_length=50),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='primary_metric_type',
            field=models.CharField(default='dice', help_text='Primary metric type (dice, iou, accuracy, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='train_metric_name',
            field=models.CharField(default='Training Dice', help_text='Display name for training metric', max_length=50),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='val_metric_name',
            field=models.CharField(default='Validation Dice', help_text='Display name for validation metric', max_length=50),
        ),
    ]
