# Network Configuration for MLManager
# Production-ready network setup with proper isolation

version: '3.8'

networks:
  # Frontend network for web traffic
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1
    driver_opts:
      com.docker.network.bridge.name: mlmanager-frontend

  # Backend network for internal services
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24
          gateway: 172.20.2.1
    driver_opts:
      com.docker.network.bridge.name: mlmanager-backend
    internal: true

  # Database network for data tier
  database:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
          gateway: 172.20.3.1
    driver_opts:
      com.docker.network.bridge.name: mlmanager-database
    internal: true

  # Monitoring network for metrics collection
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.4.0/24
          gateway: 172.20.4.1
    driver_opts:
      com.docker.network.bridge.name: mlmanager-monitoring
