# Generated by Django 5.2.1 on 2025-06-04 17:21

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import ml_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_type', models.CharField(default='unet', max_length=50)),
                ('batch_size', models.IntegerField(default=32)),
                ('epochs', models.IntegerField(default=100)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('validation_split', models.FloatField(default=0.2)),
                ('use_random_flip', models.BooleanField(default=True)),
                ('use_random_rotate', models.BooleanField(default=True)),
                ('use_random_scale', models.BooleanField(default=True)),
                ('use_random_intensity', models.BooleanField(default=True)),
                ('crop_size', models.IntegerField(default=128)),
                ('num_workers', models.IntegerField(default=4)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for new trainings')),
                ('created_by', models.CharField(blank=True, help_text='Template creator', max_length=100)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', help_text='Semantic version (e.g., 1.0.0)', max_length=50)),
                ('unique_identifier', models.CharField(blank=True, help_text='Unique model identifier', max_length=100, unique=True)),
                ('model_family', models.CharField(blank=True, help_text='Model family/category (e.g., UNet-Coronary)', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mlflow_run_id', models.CharField(max_length=50, unique=True)),
                ('model_directory', models.CharField(blank=True, help_text='Path to organized model directory', max_length=500)),
                ('model_weights_path', models.CharField(blank=True, help_text='Path to model weights file', max_length=500)),
                ('model_config_path', models.CharField(blank=True, help_text='Path to model config file', max_length=500)),
                ('training_data_info', models.JSONField(default=ml_manager.models.default_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Training dataset metadata')),
                ('model_architecture_info', models.JSONField(default=ml_manager.models.default_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Model architecture details')),
                ('performance_metrics', models.JSONField(default=ml_manager.models.default_dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Detailed performance metrics')),
                ('status', models.CharField(choices=[('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived'), ('deployed', 'Deployed')], default='training', max_length=20)),
                ('current_epoch', models.IntegerField(default=0)),
                ('total_epochs', models.IntegerField(default=0)),
                ('train_loss', models.FloatField(default=0.0)),
                ('val_loss', models.FloatField(default=0.0)),
                ('train_dice', models.FloatField(default=0.0)),
                ('val_dice', models.FloatField(default=0.0)),
                ('best_val_dice', models.FloatField(default=0.0)),
                ('stop_requested', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_family', 'version'], name='ml_manager__model_f_c4b052_idx'), models.Index(fields=['status', 'created_at'], name='ml_manager__status_6caf66_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='predictions/inputs/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='predictions/outputs/')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_manager.mlmodel')),
            ],
        ),
    ]
