# Generated by Django 5.2.2 on 2025-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='Whether model is registered in MLflow Registry'),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='registry_model_name',
            field=models.CharField(blank=True, help_text='Model name in MLflow Registry', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='registry_model_version',
            field=models.CharField(blank=True, help_text='Model version in MLflow Registry', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='registry_stage',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('Staging', 'Staging'), ('Production', 'Production'), ('Archived', 'Archived')], help_text='Current stage in MLflow Registry', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='mlflow_run_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
