# Generated by Django 5.2.2 on 2025-06-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0005_mlmodel_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='registry_model_name',
            field=models.CharField(blank=True, default='', help_text='Model name in MLflow Registry', max_length=200),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='registry_model_version',
            field=models.CharField(blank=True, default='', help_text='Model version in Registry', max_length=50),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='registry_stage',
            field=models.CharField(choices=[('None', 'None'), ('Staging', 'Staging'), ('Production', 'Production'), ('Archived', 'Archived')], default='None', help_text='Model stage in Registry', max_length=20),
        ),
    ]
