# Generated by Django 5.2.2 on 2025-06-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0008_trainingtemplate_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtemplate',
            name='device',
            field=models.CharField(default='auto', help_text='Device to use for training. Auto will use CUDA if available.', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingtemplate',
            name='model_type',
            field=models.CharField(default='unet', help_text='Model architecture type (e.g., unet, unet-old)', max_length=50),
        ),
    ]
