# Generated by Django 5.2.2 on 2025-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_manager', '0009_alter_trainingtemplate_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='current_batch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='total_batches_per_epoch',
            field=models.IntegerField(default=0),
        ),
    ]
